---
# Red Base
domain_name: "lab.local"
network_subnet: "192.168.33.0"
network_mask: "255.255.255.0"

# Configuración DNS
dns_server_ip: "192.168.33.10"
dns_forwarders:
  - "8.8.8.8"
  - "1.1.1.1"

# Configuración DHCP
dhcp_range_start: "192.168.33.100"
dhcp_range_end: "192.168.33.200"
dhcp_gateway: "192.168.33.1"
dhcp_broadcast: "192.168.33.255"