name: Ansible DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ANSIBLE_FORCE_COLOR: '1'
  ANSIBLE_HOST_KEY_CHECKING: 'false'

jobs:
  lint-and-sec:
    name: Code Quality & Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Linting Tools
        run: pip install ansible-lint

      - name: Install Ansible Collections
        run: ansible-galaxy collection install ansible.posix

      - name: Run Ansible Lint
        run: ansible-lint site.yml

      - name: Trivy IaC Security Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          hide-progress: false
          format: 'table'
          severity: 'CRITICAL,HIGH'

  dry-run:
    name: Syntax & Dry Run
    runs-on: ubuntu-latest
    # LA MAGIA: Corremos este job dentro de un contenedor nativo de Rocky Linux
    container:
      image: rockylinux:9
    steps:
      - name: Prepare Rocky Container
        # Instalamos Git, Tar (necesario para las colecciones) y Ansible
        run: |
          dnf install -y epel-release git tar
          dnf install -y ansible-core

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Ansible Collections
        run: ansible-galaxy collection install ansible.posix

      - name: Create Dummy Inventory for CI
        run: |
          mkdir -p inventory
          echo "[dns_dhcp_servers]" > inventory/hosts.ini
          echo "localhost ansible_connection=local" >> inventory/hosts.ini

      - name: Ansible Syntax Check
        run: ansible-playbook --syntax-check site.yml -i inventory/hosts.ini

      - name: Ansible Check Mode (Dry Run)
        run: ansible-playbook site.yml -i inventory/hosts.ini --check

  molecule-test:
    name: Test Role - ${{ matrix.role }}
    runs-on: ubuntu-latest
    needs: dry-run
    strategy:
      fail-fast: false
      matrix:
        role: [dns_bind, dhcpd]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Molecule & Docker Driver
        run: pip install "molecule-plugins[docker]" ansible-core

      - name: Run Molecule Test
        env:
          MOLECULE_DISTRO: rockylinux:9
        run: |
          echo "Simulando pruebas de Molecule para el rol: ${{ matrix.role }}"
